   on: [workflow_dispatch]
   
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:    
       - uses: TestOrgJosh/repo-1@main
   
     call-workflow:
       uses: TestOrgJosh/repo-1/.github/workflows/called-workflow.yml@main
       with:
         username: Shinchan
